name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "sas4ta-nosql"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
        env:
          NODE_ENV: production
          X_API_KEY: ${{ secrets.X_API_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          PORT: 8000
